services:
  postgres:
    image: postgres:17.0
    hostname: ${DB_HOST}
    ports:
      - '5432:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    hostname: redis
    ports:
      - '6379:${REDIS_PORT}'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    volumes:
      - redisdata:/data
  app:
    build: .
    ports:
      - '6969:${PORT}'
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # if you want docker to manage your dist file separately then uncomment the below line
      - /usr/src/app/dist
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/:/etc/nginx/certs
    depends_on:
      - app
volumes:
  pgdata:
  redisdata:
