services:
  db:
    image: postgres:17.0
    hostname: ${DB_HOST}
    ports:
      - '5432:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7.2-alpine
    hostname: redis
    ports:
      - '6379:${REDIS_PORT}'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:
