import { DateTime } from 'luxon';
import { habitSchedules } from './habitSchedules';
import { users } from './users';
import { randomUUID } from 'crypto';
import { HabitCompletionStatus } from '../schema';

const now = DateTime.now().toUTC().toJSDate();

export const habitCompletions = [
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[0].id,
    userId: users[0].id,
    completionDate: DateTime.utc(2024, 1, 2).toJSDate(),
    description: 'Finished reading for 30 mins.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[1].id,
    userId: users[1].id,
    completionDate: DateTime.utc(2024, 3, 4).toJSDate(),
    description: 'Jogged in the morning.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[2].id,
    userId: users[2].id,
    completionDate: DateTime.utc(2024, 2, 18).toJSDate(),
    description: 'Wrote a new blog post.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[3].id,
    userId: users[3].id,
    completionDate: DateTime.utc(2024, 4, 10).toJSDate(),
    description: 'Completed TS lesson.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[4].id,
    userId: users[4].id,
    completionDate: DateTime.utc(2024, 2, 1).toJSDate(),
    description: 'Meal prepped for the week.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[5].id,
    userId: users[5].id,
    completionDate: DateTime.utc(2024, 3, 1).toJSDate(),
    description: 'Built login screen.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[6].id,
    userId: users[6].id,
    completionDate: DateTime.utc(2024, 1, 10).toJSDate(),
    description: 'Meditated in the morning.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[7].id,
    userId: users[7].id,
    completionDate: DateTime.utc(2024, 4, 5).toJSDate(),
    description: 'Practiced guitar.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[8].id,
    userId: users[8].id,
    completionDate: DateTime.utc(2024, 4, 10).toJSDate(),
    description: 'Coded for an hour.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    habitScheduleId: habitSchedules[9].id,
    userId: users[9].id,
    completionDate: DateTime.utc(2024, 6, 2).toJSDate(),
    description: 'Wrote a paragraph.',
    status: 'completed' as HabitCompletionStatus,
    createdAt: now,
    updatedAt: now,
  },
];
