import { DateTime } from 'luxon';
import { randomUUID } from 'crypto';
import { users } from './users';
import type { GoalStatus } from '../schema';

const now = DateTime.now().toUTC().toJSDate();

export const goals = [
  {
    id: randomUUID(),
    userId: users[0].id,
    title: 'Read 12 Books',
    description: 'Read a new book every month.',
    startDate: DateTime.utc(2024, 1, 1).toJSDate(),
    endDate: DateTime.utc(2014, 12, 31).toJSDate(),
    status: 'in-progress' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[1].id,
    title: 'Run a Marathon',
    description: 'Train for and complete a marathon.',
    startDate: DateTime.utc(2024, 3, 1).toJSDate(),
    endDate: DateTime.utc(2024, 10, 15).toJSDate(),
    status: 'not-started' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[2].id,
    title: 'Start a Blog',
    description: 'Publish tech articles online.',
    startDate: DateTime.utc(2024, 2, 1).toJSDate(),
    endDate: DateTime.utc(2024, 6, 1).toJSDate(),
    status: 'completed' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[3].id,
    title: 'Learn TypeScript',
    description: 'Complete advanced TypeScript course.',
    startDate: DateTime.utc(2024, 4, 1).toJSDate(),
    endDate: DateTime.utc(2024, 9, 1).toJSDate(),
    status: 'in-progress' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[4].id,
    title: 'Lose 5kg',
    description: 'Achieve fitness goals.',
    startDate: DateTime.utc(2024, 1, 10).toJSDate(),
    endDate: DateTime.utc(2024, 6, 10).toJSDate(),
    status: 'paused' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[5].id,
    title: 'Develop Mobile App',
    description: 'Build and release a productivity app.',
    startDate: DateTime.utc(2024, 2, 10).toJSDate(),
    endDate: DateTime.utc(2024, 12, 1).toJSDate(),
    status: 'in-progress' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[6].id,
    title: 'Daily Meditation',
    description: '10 minutes meditation every morning.',
    startDate: DateTime.utc(2024, 1, 1).toJSDate(),
    endDate: DateTime.utc(2024, 12, 31).toJSDate(),
    status: 'in-progress' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[7].id,
    title: 'Learn Guitar',
    description: 'Practice guitar 3 times a week.',
    startDate: DateTime.utc(2024, 3, 1).toJSDate(),
    endDate: DateTime.utc(2024, 11, 1).toJSDate(),
    status: 'not-started' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[8].id,
    title: 'Complete 100 Days of Code',
    description: 'Code every day for 100 days.',
    startDate: DateTime.utc(2024, 4, 1).toJSDate(),
    endDate: DateTime.utc(2024, 7, 10).toJSDate(),
    status: 'in-progress' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: randomUUID(),
    userId: users[9].id,
    title: 'Write a Short Story',
    description: 'Finish and submit a short story.',
    startDate: DateTime.utc(2024, 6, 1).toJSDate(),
    endDate: DateTime.utc(2024, 8, 1).toJSDate(),
    status: 'not-started' as GoalStatus,
    createdAt: now,
    updatedAt: now,
  },
];
