@baseURL = http://localhost:6969
@urlPath = api/v1
@authPath = auth

### Verify Request
POST {{baseURL}}/{{urlPath}}/{{authPath}}/signup
Content-Type: application/json

{
  "email": "jazmyn.kunze@ethereal.email",
  "password": "password123",
  "firstname": "John",
  "lastname": "Doe"
}
