@baseURL = http://localhost:6969
@urlPath = api/v1
@authPath = auth

### Signup Request
POST {{baseURL}}/{{urlPath}}/{{authPath}}/verify-email
Content-Type: application/json

{
  "email": "jazmyn.kunze@ethereal.email",
  "token": "ffe173"
}