@baseURL = http://localhost:6969
@urlPath = api/v1
@authPath = auth

### Signup Request
POST {{baseURL}}/{{urlPath}}/{{authPath}}/verify-email
Content-Type: application/json

{
  "email": "humberto.hills@ethereal.email",
  "token": "23e06076-b97d-4d29-b2a8-7af3661398f6"
}